version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: social_hub
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234"]
      timeout: 20s
      retries: 10
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    container_name: spring-app-social_hub
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile  # Specify the Dockerfile to use
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_PORT: 3306    # we are in same network so we connect internally.
